language: python

sudo: false

env:
  global:
    - COVERAGE=true

matrix:
  fast_finish: true
  include:
  - python: 3.5
    env:
    - PYTHON=3.5
  - python: 3.5
    env:
    - PYTHON=3.6

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda3.sh
  - chmod +x miniconda3.sh
  - ./miniconda3.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - export PATH=/home/travis/miniconda2/bin:$PATH
  - conda update --yes --quiet conda
  # Install packages
  - conda create --yes --quiet -n panel-test python=${PYTHON} numpy scipy pandas xarray pytest sphinx
  - source activate panel-test

install:
  - python setup.py develop

script:
  - pytest -v panel

after_success:
  - cd doc && make html