language: python

sudo: false

env:
  global:
    - COVERAGE=true

matrix:
  fast_finish: true
  include:
  - python: 2.7
    env:
    - PYTHON=2.7
  - python: 2.7
    env:
    - PYTHON=3.4
  - python: 2.7
    env:
    - PYTHON=3.5

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - export PATH=/home/travis/miniconda2/bin:$PATH
  - conda update --yes --quiet conda

# Install packages
install:
  - conda create --yes --quiet -n panel-test python=${PYTHON} nose pip setuptools numpy pandas xarray
  - source activate panel-test
  - python setup.py install

script:
  - cd ~
  - nosetests -vv panel