language: python

sudo: false

env:
  global:
    - COVERAGE=true

matrix:
  fast_finish: true
  include:
  - python: 2.7
    env:
    - PYTHON=2.7
  - python: 2.7
    env:
    - PYTHON=3.5
  - python: 2.7
    env:
    - PYTHON=3.6

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - export PATH=/home/travis/miniconda2/bin:$PATH
  - conda update --yes --quiet conda
  # Install packages
  - conda create --yes --quiet -n panel-test python=${PYTHON} numpy pandas xarray pytest sphinx
  - source activate panel-test

install:
  - python setup.py develop

script:
  - pytest -v panel

after_success:
  - cd doc && make html